#! /bin/bash

set -e

MAJOR=$1
MINOR=$2
VERSION=$MAJOR.$MINOR

curl -O http://www.byond.com/download/build/${MAJOR}/${VERSION}_byond_linux.zip
unzip ${VERSION}_byond_linux.zip
mv byond ${VERSION}
mv ${VERSION}_byond_linux.zip ${VERSION}/

