#! /bin/bash

set -euo pipefail

rendertemplate() {
python3 -c '
import os
import sys
import yaml
from jinja2 import Environment, FileSystemLoader

env = Environment(loader=FileSystemLoader("dot"))

template = env.from_string(sys.stdin.read())

hostname = os.uname()[1]

with open("machine/default.yaml", "r") as f:
	machine = yaml.load(f)

try:
	with open("machine/{}.yaml".format(hostname), "r") as f:
		machine.update(yaml.load(f))
except FileNotFoundError:
	pass

print(template.render(**{
	"host": hostname,
	"machine": machine,
	"env": os.environ,
}))
'
}

cd "$(readlink -f .)"

find dot -type f -o -type l | while read -r f; do
	if [[ "$f" =~ \.j2$ ]]; then
		f="${f%.j2}"
		rendered="rendered/${f#dot/}"
		mkdir -p "$(dirname "$rendered")"
		rendertemplate < "$f.j2" > "$rendered"

		target="$(readlink -f "$rendered")"
	else
		target="$(readlink -f "$f")"
	fi

	location="$HOME/.${f#dot/}"

	if [[ -h "$location" ]]; then
		rm "$location"
	elif [[ -e "$location" ]]; then
		echo "$location exists and is not a symlink, skipping!"
		continue
	fi

	mkdir -p "$(dirname "$location")"

	echo "$location => $f"
	ln -s "$target" "$location"
done
