#! /bin/bash

[[ -e /tmp/screen.png ]] && rm /tmp/screen.png
scrot -z /tmp/screen.png
gm convert /tmp/screen.png -filter point -resize 10% -resize 1000% "/tmp/screen-obf.png"

killall -SIGUSR1 dunst
i3lock --pass-media-keys -n -i /tmp/screen-obf.png
killall -SIGUSR2 dunst
