

set nocompatible " Vim, not vi
filetype off

if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!curl --create-dirs -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin() " start plug

" Visual:
" Plug 'bling/vim-airline'
" Plug 'edkolev/tmuxline.vim'

" Utils:
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-surround'
Plug 'majutsushi/tagbar', { 'on': 'TagbarToggle' }
Plug 'ctrlpvim/ctrlp.vim', { 'on': 'CtrlP' }
Plug 'w0rp/ale'

" Fugitive:
" Needed for lazy loading :(
Plug 'tpope/vim-fugitive', { 'on': [] }

command! Gstatus call LazyLoadFugitive('Gstatus')
command! Gdiff call LazyLoadFugitive('Gdiff')
command! Glog call LazyLoadFugitive('Glog')
command! Gblame call LazyLoadFugitive('Gblame')

function! LazyLoadFugitive(cmd)
  call plug#load('vim-fugitive')
  call fugitive#detect(expand('%:p'))
  exe a:cmd
endfunction

" Languages:
Plug 'pearofducks/ansible-vim'
Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoInstallBinaries' }
Plug 'wlue/vim-dm-syntax', { 'for': 'dm' }
Plug 'cespare/vim-toml', { 'for': 'toml' }
Plug 'vim-scripts/indentpython.vim', { 'for': 'python' }

" Testing:
Plug 'romainl/vim-qf'
Plug 'itchyny/lightline.vim'

call plug#end()
filetype plugin indent on

let g:loaded_getscriptPlugin   = 1
let g:loaded_gzip              = 1
let g:loaded_logiPat           = 1
let g:loaded_rrhelper          = 1
let g:loaded_tarPlugin         = 1
let g:loaded_vimballPlugin     = 1
let g:loaded_zipPlugin         = 1

set rtp+=~/dotfiles/vim " Include custom non-plugin Vim things

map <F2> :NERDTreeToggle<CR>
map <F3> :TagbarToggle<CR>

let g:airline_theme = "theme"
let g:lightline = {
	\ 'colorscheme': 'theme',
	\ 'separator': { 'left': '', 'right': '' },
	\ 'subseparator': { 'left': '', 'right': '' },
	\ 'active': {
	\	'left': [
	\		[ 'mode', 'paste' ],
	\		[ 'fileinfo' ],
	\		[ 'tag' ],
	\	],
	\	'right': [
	\		[ 'aleE', 'aleW', 'lineinfo' ],
	\		[ 'percent' ],
	\		[ 'fileformat', 'fileencoding', 'filetype' ],
	\	],
	\ },
	\ 'inactive': {
	\	'left': [
	\		[ 'mode', 'paste' ],
	\		[ 'fileinfo' ],
	\	],
	\	'right': [
	\		[ 'lineinfo' ],
	\	],
	\ },
	\ 'component_function': {
	\	'fileinfo': 'status#fileinfo',
	\ },
	\ 'component_expand': {
	\	'aleE': 'status#aleE',
	\	'aleW': 'status#aleW',
	\ },
	\ 'component_type': {
	\ 	'aleE': 'error',
	\ 	'aleW': 'warning',
	\ }
	\ }
autocmd User ALELint call lightline#update() " Update status bar on lint.

" Allow tabs followed by spaces, but not the other way around
" This allows tabs for indentation, spaces for alignment, e.g.
" --->--->some_function(foo,
" --->--->              bar,
" --->--->              baz)
" (---> represents a tab, spaces represent themselves)
let g:airline#extensions#whitespace#mixed_indent_algo = 2

" Disable Airline fonts and set separators to an empty string - this gives a
" blockier appearance, but doesn't require any fancy fonts
let g:airline_powerline_fonts = 0
let g:airline_left_sep = ""
let g:airline_left_alt_sep = ""
let g:airline_right_sep = ""
let g:airline_right_alt_sep = ""

" Disable tmuxline's separators too
let g:tmuxline_separators = {
	\ "left": '',
	\ "right": '',
	\ "left_alt": '',
	\ "right_alt": ''}

let g:go_metalinter_autosave = 0
let g:go_fmt_autosave = 0

let g:ale_sign_column_always = 1
let g:ale_linters = {
	\ 'go': 'all',
	\ 'json': 'all',
	\}
" ['go build', 'gofmt', 'golint', 'gometalinter', 'gosimple', 'go vet', 'staticcheck'],


" Lint Python 2 scripts with 'python2 -m flake8' instead of 'python3 -m flake8'
autocmd FileType python
			\ if getline(1) =~ '^#!.*\<python3\>' |
			\     let b:ale_python_flake8_executable = 'python3' |
			\ endif

let g:ale_python_flake8_executable = 'python2'
let g:ale_python_flake8_options = '-m flake8'

let g:ale_go_gotype_lint_package = 1
let g:ale_go_gosimple_lint_package = 1
let g:ale_go_staticcheck_lint_package = 1
let g:ale_go_gometalinter_lint_package = 1
let g:ale_go_gometalinter_options = "--disable gocyclo --concurrency 1"
let g:ale_fixers = {
	\ 'json': 'fixjson',
	\ 'go': 'gofmt',
	\}
let g:ale_fix_on_save = 1

" Vertical split separator is a space
set fillchars+=vert:\  " comment to stop airline yelling about trailing spaces

" map :w!! to write root-only files
cnoremap w!! w !sudo tee >/dev/null %

" add ansible yaml syntax for jinja2 yaml templates
let g:ansible_extra_syntaxes = "yaml.vim"

if has("autocmd")
	autocmd BufRead PKGBUILD :set ft=PKGBUILD
endif

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set lazyredraw
set ttyfast
set ffs=unix,mac,dos
set encoding=utf-8
set autoread
set nobackup
set noswapfile
set nowritebackup
set noshowmode

set nojoinspaces

set laststatus=2

set wildignore+=*.pyc,*_build/*,*/coverage/*

set history=50    " keep 50 lines of command line history
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set number        " show line numbers
set nowrap        " don't wrap long lines automatically
set sidescroll=2

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

if has('clipboard')
	set clipboard=unnamedplus
endif

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
	set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
syntax on
set hlsearch
colors mycolors

" Only do this part when compiled with support for autocommands.
if has("autocmd")

	" Enable file type detection.
	" Use the default filetype settings, so that mail gets 'tw' set to 72,
	" 'cindent' is on in C files, etc.
	" Also load indent files, to automatically do language-dependent indenting.
	filetype plugin indent on

	" Put these in an autocmd group, so that we can delete them easily.
	augroup vimrcEx
	au!

	" For all text files set 'textwidth' to 78 characters.
	autocmd FileType text setlocal textwidth=78

	" When editing a file, always jump to the last known cursor position.
	" Don't do it when the position is invalid or when inside an event handler
	" (happens when dropping a file on gvim).
	" Also don't do it when the mark is in the first line, that is the default
	" position when opening a file.
	autocmd BufReadPost *
		\ if line("'\"") > 1 && line("'\"") <= line("$") |
		\ exe "normal! g`\"" |
		\ endif

	augroup END

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
	command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		\ | wincmd p | diffthis
endif

set noautoindent    " Disable auto-indenting
set noexpandtab     " Don't expand tabs to spaces
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=4
set tabstop=4       " Tabs are 4 spaces wide

" Fenced languages for GHFM, ie ["python"] enables Python highlighting for:
" ```python
" def foo():
"     return 2
" ```
let g:markdown_fenced_languages = ["python", "sh", "json", "javascript", "dm"]
