#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap gb "" pc105 caps:none
xmodmap ~/.Xmodmap

. ~/dotfiles/bashrc/0_path_utils.sh
. ~/dotfiles/bashrc/env.sh

pactl upload-sample ~/dotfiles/bwoink.ogg x11-bell
pactl load-module module-x11-bell sample=x11-bell
xset b on
xset b 100

export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
exec i3
