
memstats2: memstats2.c
	gcc -o memstats2 memstats2.c
	sudo chown root memstats2
	sudo chmod u+s memstats2

memstats: memstats.c
	gcc -o memstats memstats.c
	sudo chown root memstats
	sudo chmod u+s memstats
