#! /bin/bash
set -euo pipefail
cd "$(readlink -f .)"

remove_from_path() {
	<<<"$1" tr : '\n' | sed "/$(dirname "$2" | sed 's/\//\\\//g')/d" | tr '\n' : | sed -E 's/:+$//g'
}

main_executable="$0"
PATH_mod="$PATH"
while [[ "$(readlink -f "$main_executable")" == "$(readlink -f "$0")" ]]; do
	PATH_mod="$(remove_from_path "$PATH_mod" "$main_executable")"
	main_executable="$(PATH="$PATH_mod" which "$(basename "$0")")"
done
exec "$main_executable" "$@"
