#! /bin/bash

if [[ $# < 1 || $1 == "" ]]; then
	echo "please provide a modset name"
	exit 1
fi

cd ~/.factorio

if [[ -e mods ]]; then
	if [[ ! -h mods ]]; then
		echo "mods is not a symlink!"
		exit 1
	fi
	rm mods
fi

if [[ ! -e mods-"$1" ]]; then
	mkdir mods-"$1"
fi

ln -s mods-"$1" mods

exec factorio
