#! /bin/bash

findkey() {
	cat "$1" | awk '{ if(match($0, /^\s+"'"$2"'"\s+"(.*)"$/, arr)) print arr[1] }'
}

WINE=false
NEW=false
while [[ $# > 0 ]]; do
	if [[ $1 == "wine" ]]; then
		WINE=true
	elif [[ $1 == "new" ]]; then
		NEW=true
	fi
	shift
done

getcurrentbinary() {
	appid=$1
	
	cd ~/bin/scripts/steam
	if $WINE; then
		grep -lE "^exec winep steam64 \"C:/Program Files \(x86\)/Steam/Steam.exe\" steam://run/$appid$" *
	else
		grep -lE "^exec steam steam://run/$appid$" *
	fi
}

getbinname() {
	gamename=$1
	defaultstr=""
	if [[ "$2" != "" ]]; then
		defaultstr=" [$2]"
	fi
	echo -n "Binary name for $gamename$defaultstr: " 1>&2
	read binary
	echo $binary
}

if $WINE; then
	manifestspath="$HOME/wine/steam64/drive_c/Program Files (x86)/Steam/steamapps"
else
	manifestspath="$HOME/.local/share/Steam/steamapps"
fi

for k in "$manifestspath"/appmanifest*.acf; do
	this_appid=$(findkey "$k" appid)
	this_name=$(findkey "$k" name)

	default=$(getcurrentbinary "$this_appid")
	if $NEW && [[ $default != "" ]]; then
		continue
	fi
	binary=$(getbinname "$this_name" "$default")
	if [[ $binary == "" ]]; then
		continue
	fi
	if [[ -e ~/bin/scripts/steam/$binary ]]; then
		echo ~/bin/scripts/steam/$binary already exists, not overwriting!
		continue
	fi

	if $WINE; then
		cat <<EOF > ~/bin/scripts/steam/$binary
#! /bin/bash

exec winep steam64 "C:/Program Files (x86)/Steam/Steam.exe" steam://run/$this_appid
EOF
	else
		cat <<EOF > ~/bin/scripts/steam/$binary
#! /bin/bash

exec steam steam://run/$this_appid
EOF
	fi
	chmod +x ~/bin/scripts/steam/$binary
	echo "created $binary -> steam://run/$this_appid"
done
