#! /bin/bash

id=$(cat /dev/urandom | head -c4 | xxd -g4 | cut -d' ' -f2)

create="tmux new-session -n main -ds"

for cmd in $(seq 1 $1); do
    $create $id
    tmux join-pane -s temp -t main 2>/dev/null
    tmux select-layout even-horizontal

    create="tmux new-window -n temp -t"
done

tmux setw synchronize-panes on
tmux a -t $id

