#! /bin/bash

i=1
d=false
while (( i < $# )) && [[ "${!i}" =~ ^- ]]; do
	n=0
	case "${!i}" in
		--) d=true;;
		-n) n=2;;
		-p) n=2;;
		-v) n=1;;
		-t) n=1;;
		*)
			echo "unrecognised argument ${!i}"
			exit 1
			;;
	esac
	(( i = i + n ))
	if [[ "$d" == "true" ]]; then
		break
	fi
done
argsi="$i"
[[ "$d" == "true" ]] && (( argsi++ ))
cmds=()
prefix="-"
for server in "${@:$argsi}"; do
	cmds=( "${cmds[@]}" "ssh $server" )
	prefix="$prefix${server//./·}-"
done
multicmd -p "${prefix:1}" "${@:1:$((i-1))}" -- "${cmds[@]}"
