#! /bin/bash

args=()
while [[ "$1" =~ ^- ]]; do
	if [[ "$1" == "--" ]]; then
		shift
		break
	fi
	args=( "${args[@]}" "$1" )
	shift
done
cmds=()
for server in "$@"; do
	cmds=( "${cmds[@]}" "ssh $server" )
done
multicmd "${args[@]}" -- "${cmds[@]}"
