#! /bin/bash

if [[ "$1" == "" ]]; then
	name_format="%Y-%m-%d_%H-%M-%S.png"
	name="$(date +"$name_format")"
	if [[ $SCREENSHOT_FULL_SCREEN == 1 ]]; then
		ARGS="$HOME/Pictures/$name"
	else
		ARGS="-s $HOME/Pictures/$name"
	fi
	if scrot $ARGS; then # -s "$HOME/Pictures/$name"; then
		if [[ $(hostname) == "bp-arch" ]]; then
			chromium "$HOME/Pictures/$name"
		else
			termite -e "$0 $name"
		fi
	fi
else
	name="$1"
	scp -S ssh "$HOME/Pictures/$name" "thanatos.gn32.uk:www/i/$name"
	xdg-open "http://thanatos.gn32.uk/i/$name"
fi
