#! /bin/bash

title=$(playerctl metadata title)
if [[ "$title" == "Spotify – Home" ]]; then
	espeak-ng "nothing playing"
	exit
elif [[ "$title" =~ ^(.*)\ ·\ (.*)$ ]]; then
	artist=${BASH_REMATCH[2]}
	title=${BASH_REMATCH[1]}
else
	artist=$(playerctl metadata artist)
fi

espeak-ng "artist $artist"
sleep 0.1
espeak-ng "track $title"
